apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: kind-control-plane
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kind-control-plane
  virtualRouters:
  - localASN: 65530
    podIPPoolSelector:
      matchExpressions:
      - {key: somekey, operator: NotIn, values: ['never-used-value']}
    serviceSelector:
      matchExpressions:
      - {key: somekey, operator: NotIn, values: ['never-used-value']}
    exportPodCIDR: true
    neighbors:
    - peerAddress: '172.19.0.3/32'
      peerASN: 65530
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
